#region License

//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

#endregion

namespace OpenRasta.Tests.Unit.Codecs.CodecRepository
{
    using NUnit.Framework;

    public class when_registering_a_codec : codec_repository_context
    {
        [Test]
        public void the_same_codec_can_be_registered_for_several_content_types()
        {
        }

        [Test]
        public void the_same_codec_can_be_registered_for_several_resource_types()
        {
        }
    }
}