#region License

//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

#endregion

namespace OpenRasta.Tests.Unit.Codecs.MediaTypeDictionary
{
    using OpenRasta.Codecs;
    using OpenRasta.Contracts.Codecs;
    using OpenRasta.Contracts.Web;
    using OpenRasta.Testing.Framework;
    using OpenRasta.Web;

    public abstract class media_type_writer_context<TCodec> : codec_context<TCodec> where TCodec : ICodec
    {
        protected IResponse Response
        {
            get
            {
                return this.Context.Response;
            }
        }
    }
}