#region License

//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

#endregion

namespace OpenRasta.Tests.Unit.Codecs.MediaTypeDictionary
{
    #region Using Directives

    using System;

    using NUnit.Framework;

    using OpenRasta.Testing.Specifications;

    #endregion

    public class when_adding_media_types : media_type_context
    {
        [Test]
        public void adding_a_null_media_type_raises_an_error()
        {
            Executing(() => GivenMediaType(null, null)).ShouldThrow<ArgumentNullException>();
        }
    }
}