#region License

//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

#pragma warning disable 169
// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global
// ReSharper disable UnusedMember.Local

#endregion

namespace OpenRasta.Tests.Unit.Codecs.MultipartFormDataCodec
{
    #region Using Directives

    using NUnit.Framework;

    using OpenRasta.Testing.Specifications;

    #endregion

    [Ignore("No content")]
    public class when_writing_multipart_formdata : context
    {
        [Test]
        public void a_form_input_value_is_encoded_correctly()
        {
        }
    }
}