namespace OpenRasta.Contracts.Web.Markup.Rendering
{
    using OpenRasta.Web.Markup.Modules;

    public interface IXhtmlTagBuilder
    {
        IBodyElement body { get; }
        IHeadElement head { get; }
        IHtmlElement html { get; }
        ITitleElement title { get; }
        IHElement h1 { get; }
        IHElement h2 { get; }
        IHElement h3 { get; }
        IHElement h4 { get; }
        IHElement h5 { get; }
        IHElement h6 { get; }
        IAddressElement address { get; }
        IBlockQuoteElement blockquote { get; }
        IDivElement div { get; }
        IPElement p { get; }
        IPreElement pre { get; }
        IInlineElement abbr { get; }
        IInlineElement acronym { get; }
        IEmptyElement br { get; }
        IInlineElement cite { get; }
        IInlineElement code { get; }
        IInlineElement dfn { get; }
        IInlineElement em { get; }
        IInlineElement kbd { get; }
        IQElement q { get; }
        IInlineElement samp { get; }
        IInlineElement span { get; }
        IInlineElement strong { get; }
        IInlineElement var { get; }
        IAElement a { get; }
        IDlElement dl { get; }
        IDtElement dt { get; }
        IDdElement dd { get; }
        IListElement ul { get; }
        IListElement ol { get; }
        ILiElement li { get; }
        IInlineElement b { get; }
        IInlineElement big { get; }
        IEmptyElement hr { get; }
        IInlineElement i { get; }
        IInlineElement small { get; }
        IInlineElement sub { get; }
        IInlineElement sup { get; }
        IInlineElement tt { get; }
        IEditElement del { get; }
        IEditElement ins { get; }
        IImgElement img { get; }
        IFormElement form { get; }
        IInputTextElement inputText { get; }
        IInputTextElement inputPassword { get; }
        IInputCheckedElement inputCheckbox { get; }
        IInputCheckedElement inputRadio { get; }
        IInputElement inputSubmit { get; }
        IInputElement inputReset { get; }
        IInputElement inputFile { get; }
        IInputElement inputHidden { get; }
        IInputImageElement inputImage { get; }
        ISelectElement select { get; }
        IOptionElement option { get; }
        ITextAreaElement textarea { get; }
        IButtonElement button { get; }
        IFieldsetElement fieldset { get; }
        ILabelElement label { get; }
        ILegendElement legend { get; }
        IOptgroupElement optgroup { get; }
        IObjectElement @object { get; }
        IParamElement param { get; }
        IIFrameElement iframe { get; }
        IMetaElement meta { get; }
        IStyleElement style { get; }
        ILinkElement link { get; }
        IScriptElement script { get; }
        INoScriptElement noscript { get; }
        IBaseElement @base { get; }
        IBdoElement bdo { get; }
        ICaptionElement caption { get; }
        ITableElement table { get; }
        ITrElement tr { get; }
        IThElement th { get; }
        ITdElement td { get; }
        ITHeadElement thead { get; }
        ITBodyElement tbody { get; }
        ITFootElement tfoot { get; }
        IColElement col { get; }
        IColGroupElement colgroup { get; }
    }
}